using UnityEngine;
using UnityEngine.InputSystem;

// Simple physics-based player controller for a Roll-a-Ball style game.
// Uses the generated InputSystem_Actions wrapper found in Assets/InputSystem_Actions.inputactions
// Configure Rigidbody on the same GameObject (or drag a reference in the inspector), then adjust
// Speed and Max Speed to taste.
public class PlayerController : MonoBehaviour
{
    [Tooltip("Force multiplier applied when moving (higher = stronger acceleration)")]
    [SerializeField] private float speed = 300f;

    [Tooltip("Maximum horizontal speed (units/sec)")]
    [SerializeField] private float maxSpeed = 6f;

    [Tooltip("Torque strength applied to make the ball rotate (higher = faster spin)")]
    [SerializeField] private float torqueStrength = 10f;

    [Tooltip("Rigidbody to apply forces to. If left empty, GetComponent<Rigidbody>() will be used.")]
    [SerializeField] private Rigidbody rb;

    // Current movement input (-1..1 for X and Y)
    private Vector2 moveInput = Vector2.zero;

    // Input actions wrapper generated from the InputActions asset (expects class named InputSystem_Actions)
    private InputSystem_Actions controls;

    private void Awake()
    {
        if (rb == null) rb = GetComponent<Rigidbody>();

        // Create the input actions instance. This class is generated by the Input System when
        // the asset has "Generate C# Class" enabled and the asset name is InputSystem_Actions
        controls = new InputSystem_Actions();
    }

    private void OnEnable()
    {
        // Enable the Player action map and subscribe to Move updates
        controls.Player.Enable();
        controls.Player.Move.performed += OnMovePerformed;
        controls.Player.Move.canceled += OnMovePerformed;
    }

    private void OnDisable()
    {
        // Unsubscribe and disable to avoid duplicates / memory leaks
        controls.Player.Move.performed -= OnMovePerformed;
        controls.Player.Move.canceled -= OnMovePerformed;
        controls.Player.Disable();
    }

    private void OnMovePerformed(InputAction.CallbackContext ctx)
    {
        // Read current Vector2 input from the action (keyboard WASD or gamepad stick)
        moveInput = ctx.ReadValue<Vector2>();
    }

    private void FixedUpdate()
    {
        if (rb == null) return;

        // Convert 2D input to world X,Z motion. Note: assumes camera/world forward aligns with +Z.
        Vector3 move = new Vector3(moveInput.x, 0f, moveInput.y);

        // Apply force proportional to requested input and speed. Multiplying by Time.fixedDeltaTime here
        // keeps the effect framerate-independent when using ForceMode.Force.
        rb.AddForce(move * speed * Time.fixedDeltaTime, ForceMode.Force);

        // Also apply torque to make the sphere spin visually. We convert the intended movement
        // direction into a torque vector roughly perpendicular to motion so the ball rolls.
        // The mapping below gives intuitive rolling: pushing forward spins around the X axis, etc.
        Vector3 torque = new Vector3(move.z, 0f, -move.x) * torqueStrength * Time.fixedDeltaTime;
        rb.AddTorque(torque, ForceMode.Force);

        // Limit horizontal velocity to maxSpeed while preserving vertical velocity (gravity/jumps)
        Vector3 vel = rb.linearVelocity;
        Vector3 horizontal = new Vector3(vel.x, 0f, vel.z);
        float horizontalSpeed = horizontal.magnitude;
        if (horizontalSpeed > maxSpeed)
        {
            Vector3 clamped = horizontal.normalized * maxSpeed;
            rb.linearVelocity = new Vector3(clamped.x, vel.y, clamped.z);
        }
    }

    // Public setter to integrate with UI joysticks or mobile controls if needed
    public void SetMove(Vector2 input)
    {
        moveInput = input;
    }
}

